### ISSUE TITLE
回调监听的问题

### ISSUE THREAD

**Issue by HelloFish-2016** [maoabc/unrar-android#3]
请问作者这个解压的过程没有进度监听吗，起码什么时候解压结束应该有个回调吧，目前好像没有啊，

**Comment by maoabc** [comment]
UnrarCallback.processData里第二次个参数有每次解压的数据长度，RarEntry有文件未压缩前长度，根据这两个信息，实现自己的UnrarCallback就可以计算进度

**Comment by HelloFish-2016** [comment]
> UnrarCallback.processData里第二次个参数有每次解压的数据长度，RarEntry有文件未压缩前长度，根据这两个信息，实现自己的UnrarCallback就可以计算进度

是的 看到了，还有个问题，就是能通过RarFile这个文件提前判断这个文件有没有加密呢

**Comment by maoabc** [comment]
> > UnrarCallback.processData里第二次个参数有每次解压的数据长度，RarEntry有文件未压缩前长度，根据这两个信息，实现自己的UnrarCallback就可以计算进度
> 
> 是的 看到了，还有个问题，就是能通过RarFile这个文件提前判断这个文件有没有加密呢

通过getEntries得到RarEntry去判断是否加密, 如果rar整个都被加密, getEntries的参数回调接口的needPassword方法会被调用

**Comment by maoabc** [comment]
> > > UnrarCallback.processData里第二次个参数有每次解压的数据长度，RarEntry有文件未压缩前长度，根据这两个信息，实现自己的UnrarCallback就可以计算进度
> > 
> > 
> > 是的 看到了，还有个问题，就是能通过RarFile这个文件提前判断这个文件有没有加密呢
> 
> 通过getEntries得到RarEntry去判断是否加密, 如果rar整个都被加密, getEntries的参数回调接口的needPassword方法会被调用

在openArchive0增加flags参数, 通过它来判断rar是否整体加密.

**Comment by HelloFish-2016** [comment]
> > > UnrarCallback.processData里第二次个参数有每次解压的数据长度，RarEntry有文件未压缩前长度，根据这两个信息，实现自己的UnrarCallback就可以计算进度
> > 
> > 
> > 是的 看到了，还有个问题，就是能通过RarFile这个文件提前判断这个文件有没有加密呢
> 
> 通过getEntries得到RarEntry去判断是否加密, 如果rar整个都被加密, getEntries的参数回调接口的needPassword方法会被调用

如果整个rar文件被加密了，默认情况下我是不知道文件有没有加密，所以getEntries拿不到RarEntry的，不知道这能不能作为一种判断是否加密的方法

**Comment by HelloFish-2016** [comment]
> > > > UnrarCallback.processData里第二次个参数有每次解压的数据长度，RarEntry有文件未压缩前长度，根据这两个信息，实现自己的UnrarCallback就可以计算进度
> > > 
> > > 
> > > 是的 看到了，还有个问题，就是能通过RarFile这个文件提前判断这个文件有没有加密呢
> > 
> > 
> > 通过getEntries得到RarEntry去判断是否加密, 如果rar整个都被加密, getEntries的参数回调接口的needPassword方法会被调用
> 
> 在openArchive0增加flags参数, 通过它来判断rar是否整体加密.

请问下，openArchive的flag参数有三个值RAR_OM_LIST，RAR_OM_EXTRACT，RAR_OM_LIST_INCSPLIT大概是什么意思呢

**Comment by maoabc** [comment]
> > > > > UnrarCallback.processData里第二次个参数有每次解压的数据长度，RarEntry有文件未压缩前长度，根据这两个信息，实现自己的UnrarCallback就可以计算进度
> > > > 
> > > > 
> > > > 是的 看到了，还有个问题，就是能通过RarFile这个文件提前判断这个文件有没有加密呢
> > > 
> > > 
> > > 通过getEntries得到RarEntry去判断是否加密, 如果rar整个都被加密, getEntries的参数回调接口的needPassword方法会被调用
> > 
> > 
> > 在openArchive0增加flags参数, 通过它来判断rar是否整体加密.
> 
> 请问下，openArchive的flag参数有三个值RAR_OM_LIST，RAR_OM_EXTRACT，RAR_OM_LIST_INCSPLIT大概是什么意思呢

RAR_OM_LIST是只读取RarHeader, RAR_OM_EXTRACT解压或者通过回调取数据时使用, RAR_OM_LIST_INCSPLIT不是很清楚
