### ISSUE TITLE
麻烦问下, 用的unrar版本是多少啊?

### ISSUE THREAD

**Issue by Liloupar** [maoabc/unrar-android#5]

**Comment by maoabc** [comment]
应该是5.74, version.hpp里面这个应该准确的，后面记得不用libunrar用7zip就没再更新libunrar.
```
#define RARVER_MAJOR     5
#define RARVER_MINOR    71
#define RARVER_BETA      0
#define RARVER_DAY      28
#define RARVER_MONTH     4
#define RARVER_YEAR   2019
```

**Comment by Liloupar** [comment]
> 应该是5.74, version.hpp里面这个应该准确的，后面记得不用libunrar用7zip就没再更新libunrar.
> 
> ```
> #define RARVER_MAJOR     5
> #define RARVER_MINOR    71
> #define RARVER_BETA      0
> #define RARVER_DAY      28
> #define RARVER_MONTH     4
> #define RARVER_YEAR   2019
> ```

明白了 谢谢大佬
